<?php
return [
    'steam-header'   => "The steam Baths",
    'russian-header' => "The Russian bath",
    'turkish-header' => "The Turkish bath",
    'finnish-header' => "The Finnish sauna",


    'turkish-text' => "The history of Turkish bath dates to very distant times, when the Turks had not reached Antalya yet.

Arriving to Antalya they brought the ancient traditions, but also faced with another tradition - the

Romanian and Byzantine. The mixture of these two traditions has given birth to a new concept of

Turkish bath.

At first the bath was heated with warm air from the underneath. The air was transported through

special pipes, which were hidden under a marble bath floor. The Turkish bath has been heated by a

huge boiler, installed in the wall. This boiler was a steam producer. The water was boiling in the

boiler and the steam entered a bath through a large hole, located approximately 1.5 meters in height.

Modern technology and equipment allow to simplify this technical device. Now Turkish baths

contain the high quality flashing (two-layer), the double heating system with water or electricity,

hidden in reinforced concrete structures.

The classical ceiling - a dome-shaped, for the draining of the resulting condensate, at the bottom of

the dome is held the drainage. High humidity inside the bath is achieved with a steam generator; the

fragrances are generated by a fragrance dispenser. The lighting is supplied by a heat-resistant,

moisture protected bulbs (a starry sky effect). Ventilation and sewerage systems are mandatory.

The internal design can be various: European - mosaic, decorative tiles, neon lighting, Classic -

marble, columns, pilasters, mosaic chairs, bowls for washing up, fountains.",




    'russian-text'=>"Every Russian likes to have a strong hatching bath. And in fact, if a Russian has a bath, it must be

strongly heated. And if he is getting himself sauna it should be heated to not less than 120°C.

Russian temperament has influenced the way we now build sauna; we just have to keep in mind that

Russian expects much more from sauna, than the European, American and even Finn.

In Russian sauna, all is based on a single idea - to get a perfect steam, which would be beneficial to

health. Russians like extreme conditions, so the temperature in the bath can be very high (more than

120°C). Comfortable design, wood selection, proper ventilation and constant air circulation in bath

is necessary for the body to recover from the shock experienced when having a bath. You should

know that the shock is not the state from which the person immediately falls and dies. Shock - is the

body&#39;s reaction to the high temperature at which all the organs are working on a loaded mode. If this

is rear, it can be useful: adrenaline is released, the protective mechanisms are activated, the immune

system is strengthened, and the body is cleaned.

That is why there are no trivial things when building a Russian sauna. Every detail is important to

implement the main idea of sauna - the maximum heating without harmful consequences.

A lot of people think that the broom procedure is useful only for healthy people, and for those with

a weak heart, it is not suitable. We believe that this is completely untrue. You can relax at a very

low temperature and strain a human heart so that he will feel bad and vice versa. Some time spent in

a Russian sauna is useful for many patients with heart diseases.",

    'finnish-text'=>"Why do Finns go to sauna?

Because this is an old custom and people are habituated to it since childhood. Sauna is cleanliness,

health, peace of mind, emotional charge, and other pleasures.

Cleanliness

Since ancient times, it was possible to visit sauna once a week, if necessary more often. In modern

houses there is a substitute for sauna - bath tub, a shower, but sauna is still considered to be

necessary in bathrooms. The procedures in broom rooms and water procedures - cleans the skin

better than you can imagine.

Health

An old Finnish proverb tells “if sauna, vodka and resin doesn’t help, the disease is fatal”, does not

mean that everything must be used simultaneously. People were going to sauna when they felt the

need to restore tired joints and muscles.

Peace of mind

The Finnish writer F.E. Silanpia tells how he went to his parents to rest after a long period of

creative work, tired and in a bad mood. The very first night, being in a warm bath in silence, he felt

a gradually disappearing oppression. After the bath he rebuilt the inner balance. Shortly afterwards

he could write again.",


    'steam-text'=>"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are two types of baths according to the temperature and humidity: steam bath and dry heat

bath.

<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Steam bath is heated by steam, which occurs squirting the water on stones and bricks heated up to

350-400°С. The air temperature reaches approximately 68.4°С, air humidity up to 70%, if the steam

comes directly from the boiler - respectively 42.3°С and 100%.

The air temperature in dry hot air sauna (Finnish sauna), reaches 70-80°С, 120-135°С and even 200°С, the

humidity of air 15-10% and less.

<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The most important thing in the bath is steam. It is known, that during the presence in steam,

increases amount of hemoglobin, white blood cells and red blood cells in human blood, and body's

resistance to pathogenic microbes. Thanks to steam bath, the metabolic system speeds up, the

muscles relaxes, slag eliminates through the sweat glands and dead cells are eliminated from the top

layer of skin. The sauna also has a positive effect to the other systems of our body: urinary system

(especially for kidneys), endocrine, central and peripheral nervous system.

<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;During the presence in steam, while having a shower and massage in bath, the sebaceous and sweat

glands begins to function better, the blood flow and metabolism speeds up. The skin is completely

cleansed of grease, sweat, dust, dead skin cells; it becomes smooth, elastic and begins to \"breathe\".

It has been proved that a person loses up to 2 kg body weight after a visit to sauna.

Repeatedly overheated body strengthens the protective, secretion, respiratory, neutralization, endocrine,

immune, energetic and many other body functions.
",


];